### ISSUE TITLE
Add Contact DLC factions

### ISSUE THREAD

**Issue by shadow-fa** [folkarps/F3#254]
Three new factions will be added in the Contact DLC.
We would want to add gear files for these, as well as units in the template (incl. new vehicles), and group data for markers.

 - [X] group data #256 (PR merged)
 - [x] briefing #256 (PR merged)
 - [x] template units #263 
 - [x] assignGear #257 (PR merged)

(SL) For completeness, the new factions are:
 - LDF
 - Spetsnaz
 - NPR (Looters)

**Comment by NikkoJT** [comment]
Per discussion in Discord, there are outstanding issues with assignGear; particularly, NPR units need to have the correct, OPFOR, UAV terminals and UAVs in order to use them properly. @costno is said to be working on this.

**Comment by SamLex** [comment]
Spot tested with template and assignGear showcase. All looks correct.
